= Red Hat One VMA/VMF Super LAB

Hello!

Welcome to Virtualization Migration Assessment and Virtualization Migration Factory SuperLab!

It's super cool to have you joining us on this time.

.Goals
* Learn how to turn complex VMware migrations into your next big customer win.
* Master the key foundational design and sizing considerations from the VMA.
* Learn how to provision and execute the automated factory itself.

You'll leave this session with the practical skills and confidence to de-risk projects, accelerate customer adoption, and successfully deliver large-scale transformations.

Read all the topics, pay attention on the notes and tips and enjoy!

NOTE: Those who read carefully are always at an advantage.

Have fun!

Bastion Node Public Hostname:: {bastion_public_hostname}
Bastion Node SSH Password:: {bastion_ssh_password}
Bastion Node SSH Port:: {bastion_ssh_port}
Bastion SSH User Name:: {bastion_ssh_user_name}
Lab GUID:: {guid}
OpenShift API Server URL:: {openshift_api_server_url}
OpenShift Cluster Admin Password:: {openshift_cluster_admin_password}
OpenShift Admin Username:: {openshift_cluster_admin_username}
OpenShift Console URL:: {openshift_cluster_console_url}
OpenShift Cluster User:: {openshift_cluster_user_base}
Gitea User:: {gitea_user}
Gitea URL:: {gitea_console_url}
Vcenter URL:: {vcenter_url}
Vcenter User:: {vcenter_user_name}
Vcenter Password:: {vcenter_password}
Vcenter Folder:: {vcenter_vm_folder}
